### ISSUE TITLE
crash when trying to play a track from a network drive that is not mounted

### ISSUE THREAD

**Issue by xipmix** [volumio/Volumio2#1030]
I can confirm the 'NAS' issue raised in #936. Opening a new issue to keep things clear.

To reproduce (2.041):
  * connect a share in MyMusic, let the scan complete
  * ssh in and umount the share
  *  browse to the music library and try to play a track from that share. Boom.

journalctl -f:
```
volumio[1405]: info: CoreCommandRouter::volumioAddQueueItems
volumio[1405]: info: [1487945830790] CoreStateMachine::addQueueItems
volumio[1405]: info: [1487945830798] CorePlayQueue::addQueueItems
volumio[1405]: info:  uri=music-library/NAS/testrm2/Rattle_and_Hum/03-Desire.flac, title=Desire, service=mpd
volumio[1405]: info: First index is 3
volumio[1405]: info: ADDING THIS ITEM TO QUEUE: {"uri":"music-library/NAS/testrm2/Rattle_and_Hum/03-Desire.flac","title":"Desire","service":"mpd"}
volumio[1405]: info: Exploding uri music-library/NAS/testrm2/Rattle_and_Hum/03-Desire.flac in service mpd
volumio[1405]: info: ----------------------------/mnt/NAS/testrm2/Rattle_and_Hum/03-Desire.flac
volumio[1405]: fs.js:987
volumio[1405]: return binding.stat(pathModule._makeLong(path));
volumio[1405]: ^
volumio[1405]: Error: ENOENT: no such file or directory, stat '/mnt/NAS/testrm2/Rattle_and_Hum/03-Desire.flac'
volumio[1405]: at Error (native)
volumio[1405]: at Object.fs.statSync (fs.js:987:18)
volumio[1405]: at Object.statSync (/volumio/node_modules/graceful-fs/polyfills.js:289:22)
volumio[1405]: at ControllerMpd.scanFolder (/volumio/app/plugins/music_service/mpd/index.js:2006:25)
volumio[1405]: at ControllerMpd.explodeUri (/volumio/app/plugins/music_service/mpd/index.js:1932:27)
volumio[1405]: at CoreCommandRouter.explodeUriFromService (/volumio/app/index.js:1098:22)
volumio[1405]: at CorePlayQueue.addQueueItems (/volumio/app/playqueue.js:140:52)
volumio[1405]: at CoreStateMachine.addQueueItems (/volumio/app/statemachine.js:150:24)
volumio[1405]: at CoreCommandRouter.addQueueItems (/volumio/app/index.js:383:27)
volumio[1405]: at Socket.<anonymous> (/volumio/app/plugins/user_interface/websocket/index.js:131:36)
mpd[613]: client: [2] closed
```
I'm guessing this needs an exception handler?
```
// app/plugins/music_service/mpd/index.js
...
ControllerMpd.prototype.scanFolder=function(uri)                                
{                                                                               
    var self=this;                                                              
    var uris=[];                                                                

+  try {                                                                            
    var stat=libFsExtra.statSync(uri);                                          
+  } catch(err) {
+    defer.resolve({}); // more thought needed here
+  }                                                                               
```
I have been thinking about this issue of the music library being out of date with respect to what shares are mounted, which has come up a few times (eg #296). Something that might be useful would be to style the track titles in a different color or strikethrough font if they fail to play

**Comment by xipmix** [comment]
Tested this and it avoids the crash, but the user gets no feedback that something failed.
```
--- a/app/plugins/music_service/mpd/index.js
+++ b/app/plugins/music_service/mpd/index.js
@@ -2061,7 +2061,12 @@ ControllerMpd.prototype.scanFolder=function(uri)
     var self=this;
     var uris=[];
 
+    try {
     var stat=libFsExtra.statSync(uri);
+    } catch(err) {
+        console.log("scanFolder - failure to stat '" + uri + "'");
+        return uris;
+    }
 
     if(stat.isDirectory())
     {

```
Log:
```
volumio[2134]: info: CoreCommandRouter::executeOnPlugin: mpd , handleBrowseUri
volumio[2134]: info: CURURI: music-library/NAS/testrm2/Rattle_and_Hum
volumio[2134]: info: CoreCommandRouter::volumioAddQueueItems
volumio[2134]: info: [1487981236704] CoreStateMachine::addQueueItems
volumio[2134]: info: [1487981236719] CorePlayQueue::addQueueItems
volumio[2134]: info:  uri=music-library/NAS/testrm2/Rattle_and_Hum/03-Desire.flac, title=Desire, service=mpd
volumio[2134]: info: First index is 3
volumio[2134]: info: ADDING THIS ITEM TO QUEUE: {"uri":"music-library/NAS/testrm2/Rattle_and_Hum/03-Desire.flac","title":"Desire","service":"mpd"}
volumio[2134]: info: Exploding uri music-library/NAS/testrm2/Rattle_and_Hum/03-Desire.flac in service mpd
volumio[2134]: info: ----------------------------/mnt/NAS/testrm2/Rattle_and_Hum/03-Desire.flac
volumio[2134]: scanFolder - failure to stat '/mnt/NAS/testrm2/Rattle_and_Hum/03-Desire.flac'
volumio[2134]: info: [1487981236767] CorePlayQueue::saveQueue
volumio[2134]: info: Adding item to queue: []
volumio[2134]: info: CoreCommandRouter::volumioPushQueue
volumio[2134]: info: [1487981236781] interfaceApi::pushQueue
volumio[2134]: info: [1487981236783] InterfaceWebUI::pushQueue
volumio[2134]: info: [1487981236791] CoreStateMachine::updateTrackBlock
volumio[2134]: info: [1487981236793] CorePlayQueue::getTrackBlock
volumio[2134]: info: CoreCommandRouter::volumioPlay
volumio[2134]: UNSET VOLATILE
volumio[2134]: info: [1487981236802] CoreStateMachine::play index 3
volumio[2134]: info: [1487981236805] CoreStateMachine::setConsumeUpdateService undefined
volumio[2134]: info: [1487981236812] CoreStateMachine::stop
volumio[2134]: info: [1487981236813] CoreStateMachine::setConsumeUpdateService undefined
volumio[2134]: UNSET VOLATILE
volumio[2134]: info: [1487981236817] CoreStateMachine::play index undefined
volumio[2134]: info: [1487981236819] CoreStateMachine::setConsumeUpdateService undefined
volumio[2134]: info: [1487981236821] CorePlayQueue::getTrack 3

```

It might be useful to introduce a 'failed' prefix that would trigger some kind of error message display -
```
uris.push("failed+" + uri);
return uris;
```
