### ISSUE TITLE
Spotify plugin becomes "inactive"

### ISSUE THREAD

**Issue by JonathanHuot** [volumio/Volumio2#1401]
After Spotify plugin installation, it was all-green, I had the chance to search and listen music with success.
Then, suddenly, the "Spotify" menu-entry vanishes, and the green status in /plugin-manager becomes red "inactive".

I've tried to disable then re-enable, without any luck.

Then, I had a look on /var/log/volumio.log, and saw an exception, followed by a success message:
```
2017-11-22T18:09:15.857Z - info:  Error: connect ECONNREFUSED 127.0.0.1:6602
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
2017-11-22T18:09:15.859Z - info: SPOP status error:
2017-11-22T18:09:15.861Z - info:  Error: connect ECONNREFUSED 127.0.0.1:6602
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)

2017-11-22T18:09:16.413Z - info: Spotify access token expires at 1511377755836
2017-11-22T18:09:16.414Z - info: Spotify access token is xxxx-zzzzzzzzzzzzzzz
2017-11-22T18:09:16.415Z - info: Spotify credentials grant success
```

So... given the timestamp, my access token expires after the log date, then the token should be valid. However, the "inactive" red status is always there, and no menu entry.

Also, I've checked if I had a service listening on port 6602, but I don't. Maybe that's the culprit ?

```
volumio@volumio:~$ ss -tapnl|grep 6602
volumio@volumio:~$ 
```

Any ideas out there ? I'll be checking code sources to see if I can spot an obvious thing.
Thanks

**Comment by moralrebuild** [comment]
same issue, anyone can help? Thanks.
