### ISSUE TITLE
Library update does not continue after a restart

### ISSUE THREAD

**Issue by gkkpch** [volumio/Volumio2#148]
After adding a new mount, mpd starts updating the library. After a reboot, pmd does not seem to be re-starting the library update, Re-Scan gives following console output .....
EDIT: it **does** continue now!

CoreCommandRouter::executeOnPlugin: mpd , rescanDb
[1452547139723] ControllerMpd::sendMpdCommand
[1452547139728] sending command...

[1452547139753] ---------------------------- MPD announces state update
[1452547139759] parsing response...
[1452547139765] ControllerMpd::getState
[1452547139769] ControllerMpd::sendMpdCommand
[1452547139774] sending command...
[1452547139793] parsing response...
[1452547139803] ControllerMpd::parseState
[1452547139809] ControllerMpd::pushState
CoreCommandRouter::servicePushState
[1452547139822] CoreStateMachine::syncState
[1452547139826] CoreStateMachine::getState
[1452547139836] CoreStateMachine::stopPlaybackTimer
[1452547139846] CoreStateMachine::pushState
CoreCommandRouter::volumioPushState
[1452547139850] InterfaceWebUI::pushState
[1452547139855] ------------------------------ 103ms

The My Library tab does issue
CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats

and this does not give an update, though I have seen it doing that before

Using the Rebuild Volumio Library on the dev page gives the following console output:
[Event]: rebuildLibrary [Parameters]:"", undefined

[1452546818897] ---------------------------- Client requests Volumio Rebuild Library
CoreCommandRouter::volumioRebuildLibrary
Error:
TypeError: Cannot read property 'buildLibrary' of undefined
    at CoreCommandRouter.volumioRebuildLibrary (/volumio/app/index.js:184:26)
    at applyWithContext (/volumio/node_modules/fast.js/function/applyWithContext.js:13:22)
    at Promise._successFn (/volumio/node_modules/fast.js/function/bind.js:63:14)
    at nextTickCallback (/volumio/node_modules/kew/kew.js:47:28)
    at process._tickCallback (node.js:355:11)

**Comment by gkkpch** [comment]
I thought it was not updating after pressing Re-Scan, but it does. But after a reboot it does not continue automatically. The My Library Tab does not get refreshed/ updated.

**Comment by gkkpch** [comment]
Update on this issue, my sceanrio:
- fresh image from today
- set playback options
- add my music library from NAS (should take approx 25 minutes to update)
- My Music screen shows steadily increasing number of artists, albums etc.
- log shows regular getMyCollectionStats entries
- reboot after 10 minutes (for whatever reason)
- after reboot, update does not continue, My Music screen shows static numbers
- log shows regular getMyCollectionStats entries
- I hit Re-Scan, visible in volumio.log, nothing happens except Network disappearing, comes back after a few moments, no change in My Music
- log continues to show regular getMyCllectionStats, nothing happens
- reboot, no difference
- ssh into volumio and enter "mpc update /var/lib/mpd/music/NAS"
- Updating continues....
