### ISSUE TITLE
tracebacks from mpd/lib/mpd.js

### ISSUE THREAD

**Issue by xipmix** [volumio/Volumio2#1569]
This is minor (playback works ok) but I thought I should report it.
I see things like this on startup (fresh 2.413 with one song in queue)
```
Jun 22 22:04:39 volumio volumio[9897]: info: Volumio called home
Jun 22 22:04:39 volumio volumio[9897]: info: CoreCommandRouter::executeOnPlugin: alsa_controller , checkAudioDeviceAvailable
Jun 22 22:04:39 volumio volumio[9897]: info: CoreCommandRouter::executeOnPlugin: system , versionChangeDetect
Jun 22 22:04:39 volumio volumio[9897]: info: Reloading queue from file
Jun 22 22:04:39 volumio volumio[9897]: info:
Jun 22 22:04:39 volumio volumio[9897]: info:  message= [50@0] {} No such directory, stack=Error:  [50@0] {} No such directory
Jun 22 22:04:39 volumio volumio[9897]: at MpdClient.receive (/volumio/app/plugins/music_service/mpd/lib/mpd.js:63:14)
Jun 22 22:04:39 volumio volumio[9897]: at Socket.<anonymous> (/volumio/app/plugins/music_service/mpd/lib/mpd.js:43:10)
Jun 22 22:04:39 volumio volumio[9897]: at emitOne (events.js:116:13)
Jun 22 22:04:39 volumio volumio[9897]: at Socket.emit (events.js:211:7)
Jun 22 22:04:39 volumio volumio[9897]: at addChunk (_stream_readable.js:263:12)
Jun 22 22:04:39 volumio volumio[9897]: at readableAddChunk (_stream_readable.js:246:13)
Jun 22 22:04:39 volumio volumio[9897]: at Socket.Readable.push (_stream_readable.js:208:10)
Jun 22 22:04:39 volumio volumio[9897]: at Pipe.onread (net.js:607:20)
Jun 22 22:04:39 volumio volumio[9897]: info: CoreStateMachine::setRepeat null single undefined
Jun 22 22:04:39 volumio volumio[9897]: info: CoreStateMachine::pushState
Jun 22 22:04:39 volumio volumio[9897]: info: CoreStateMachine::getState
```
I took a look at the code and it seems might originate in mpdemulation:
```
    618 // Handler for command: PLAYLISTID
    619 InterfaceMPD.prototype.handlePlaylistid = function(sCommand, sParam, cli
    619 ent) {
    620         // Temporary Disabled and HardCoded
    621         client.write('ACK [50@0] {playlistid} No such song\n');
    622 
    623         // Respond with default 'OK'
    624         // client.write(okay_response);
    625 };
```
that's the only reference to '50@0' I can find.

I will reflash and retest in case my recent locale mangling adventures did something to cause this.

**Comment by volumio** [comment]
Not an issue, this is just because mpd checks if there are files on USB which might not be present anymore
