### ISSUE TITLE
/volumio/.globals.json ENOENT - Volumio doesn't start after update to latest version 2.587

### ISSUE THREAD

**Issue by CherryDT** [volumio/Volumio2#1775]
This is not the same as #1774 - this is a different error on another volumio machine! This error here is from updating from 2.411 to 2.587

```Jun 17 07:16:48 volumio volumio[1238]: /volumio/node_modules/fs-extra/node_modules/jsonfile/index.js:73
Jun 17 07:16:48 volumio volumio[1238]: throw err
Jun 17 07:16:48 volumio volumio[1238]: ^
Jun 17 07:16:48 volumio volumio[1238]: Error: /volumio/.globals.json: ENOENT: no such file or directory, open '/volumio/.globals.json'
Jun 17 07:16:48 volumio volumio[1238]: at Object.fs.openSync (fs.js:646:18)
Jun 17 07:16:48 volumio volumio[1238]: at Object.fs.readFileSync (fs.js:551:33)
Jun 17 07:16:48 volumio volumio[1238]: at Object.readFileSync (/volumio/node_modules/fs-extra/node_modules/jsonfile/index.js:67:22)
Jun 17 07:16:48 volumio volumio[1238]: at Object.<anonymous> (/volumio/index.js:3:18)
Jun 17 07:16:48 volumio volumio[1238]: at Module._compile (module.js:652:30)
Jun 17 07:16:48 volumio volumio[1238]: at Object.Module._extensions..js (module.js:663:10)
Jun 17 07:16:48 volumio volumio[1238]: at Module.load (module.js:565:32)
Jun 17 07:16:48 volumio volumio[1238]: at tryModuleLoad (module.js:505:12)
Jun 17 07:16:48 volumio volumio[1238]: at Function.Module._load (module.js:497:3)
Jun 17 07:16:48 volumio volumio[1238]: at Function.Module.runMain (module.js:693:10)
Jun 17 07:16:48 volumio systemd[1]: volumio.service: main process exited, code=exited, status=1/FAILURE
Jun 17 07:16:48 volumio systemd[1]: Unit volumio.service entered failed state.```

**Comment by CherryDT** [comment]
Workaround: Create `/volumio/.globals.json` with contents `{"exitOnException":true}`

**Comment by volumio** [comment]
Your install seems corrupted or you manually edited files
