### ISSUE TITLE
Favorites with non existing entry hangs volumio

### ISSUE THREAD

**Issue by balbuze** [volumio/Volumio2#2019]
If a track in favorites is from an unavailable service.
Steps to reproduce 
- add a track from Spotify (spopd)
- disable the plugin or use an other synchronized device
- try to play the track 
```
Nov 09 15:38:04 volumio-x86 volumio[11190]: info: Exploding uri spotify:track:6OKZLJfIGpSZmE0R7hBHBI in service spop
Nov 09 15:38:04 volumio-x86 volumio[11190]: |||||||||||||||||||||||| WARNING: FATAL ERROR |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Nov 09 15:38:04 volumio-x86 volumio[11190]: TypeError: Cannot read property 'explodeUri' of undefined
Nov 09 15:38:04 volumio-x86 volumio[11190]: at CoreCommandRouter.explodeUriFromService (/volumio/app/index.js:1281:18)
Nov 09 15:38:04 volumio-x86 volumio[11190]: at CorePlayQueue.addQueueItems (/volumio/app/playqueue.js:144:48)
Nov 09 15:38:04 volumio-x86 volumio[11190]: at CoreStateMachine.addQueueItems (/volumio/app/statemachine.js:234:25)
Nov 09 15:38:04 volumio-x86 volumio[11190]: at CoreCommandRouter.replaceAndPlay (/volumio/app/index.js:476:23)
Nov 09 15:38:04 volumio-x86 volumio[11190]: at CoreCommandRouter.playItemsList (/volumio/app/index.js:452:17)
Nov 09 15:38:04 volumio-x86 volumio[11190]: at Socket.<anonymous> (/volumio/app/plugins/user_interface/websocket/index.js:102:35)
Nov 09 15:38:04 volumio-x86 volumio[11190]: at emitTwo (events.js:126:13)
Nov 09 15:38:04 volumio-x86 volumio[11190]: at Socket.emit (events.js:214:7)
Nov 09 15:38:04 volumio-x86 volumio[11190]: at /volumio/node_modules/socket.io/lib/socket.js:503:12
Nov 09 15:38:04 volumio-x86 volumio[11190]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
Nov 09 15:38:04 volumio-x86 volumio[11190]: at process._tickCallback (internal/process/next_tick.js:180:9)
Nov 09 15:38:04 volumio-x86 volumio[11190]: |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

**Comment by volumio** [comment]
Thanks for reporting! Fixed with https://github.com/volumio/Volumio2/commit/c4347842fd74fd63a502d9c93e24fe66aefd6855
