### ISSUE TITLE
Scan of music library on network drive not completing

### ISSUE THREAD

**Issue by skikirkwood** [volumio/Volumio2#511]
On RC2 Hotfix, I have two network drives mounted on my iMac as SMB shares.  After adding them the scanning process goes for some period of time and then stops.  The first scan stopped after 3000 tracks.  Trying a fourth restart after the last scan stopped at 16,000 tracks.  My library has about 20,000 tracks.

The scan just crashed my Raspberry Pi 3.  After rebooting the two network drives did not mount.  Log file below.  Another reboot resulted in successful mounting of the two network drives.

volumio@volumio2:/var/log$ cat volumio.log 
1970-01-01T00:00:21.969Z - info: -------------------------------------------
1970-01-01T00:00:21.976Z - info: -----            Volumio2              ----
1970-01-01T00:00:21.976Z - info: -------------------------------------------
1970-01-01T00:00:21.977Z - info: -----          System startup          ----
1970-01-01T00:00:21.977Z - info: -------------------------------------------
1970-01-01T00:00:22.236Z - info: Plugin folders cleanup
1970-01-01T00:00:22.237Z - info: Scanning into folder /volumio/app/plugins/
1970-01-01T00:00:22.238Z - info: Scanning category audio_interface
1970-01-01T00:00:22.239Z - info: Scanning category miscellanea
1970-01-01T00:00:22.240Z - info: Scanning category music_service
1970-01-01T00:00:22.241Z - info: Scanning category plugins.json
1970-01-01T00:00:22.242Z - info: Scanning category system_controller
1970-01-01T00:00:22.243Z - info: Scanning category user_interface
1970-01-01T00:00:22.244Z - info: Scanning into folder /data/plugins/
1970-01-01T00:00:22.245Z - info: Scanning category music_service
1970-01-01T00:00:22.246Z - info: Plugin folders cleanup completed
1970-01-01T00:00:22.248Z - info: Loading plugins from folder /volumio/app/plugins/
1970-01-01T00:00:22.256Z - info: Loading plugins from folder /data/plugins/
1970-01-01T00:00:22.261Z - info: Loading plugin "system"...
1970-01-01T00:00:22.319Z - info: Loading plugin "appearance"...
1970-01-01T00:00:22.681Z - info: Loading plugin "i2s_dacs"...
1970-01-01T00:00:22.692Z - info: Loading plugin "network"...
1970-01-01T00:00:22.767Z - info: Loading plugin "services"...
1970-01-01T00:00:22.772Z - info: Loading plugin "alsa_controller"...
1970-01-01T00:00:22.869Z - info: Loading plugin "volumio_command_line_client"...
1970-01-01T00:00:22.877Z - info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
1970-01-01T00:00:22.878Z - info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
1970-01-01T00:00:22.879Z - info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
1970-01-01T00:00:22.910Z - info: Loading plugin "volumiodiscovery"...
1970-01-01T00:00:22.980Z - info: Applying required configuration parameters for plugin volumiodiscovery
1970-01-01T00:00:23.026Z - info: CoreCommandRouter::executeOnPlugin: system , registerCallback
1970-01-01T00:00:23.027Z - info: Loading plugin "upnp"...
1970-01-01T00:00:23.035Z - info: [23034] Starting Upmpd Daemon
1970-01-01T00:00:23.051Z - info: CoreCommandRouter::executeOnPlugin: system , registerCallback
1970-01-01T00:00:23.052Z - info: Loading plugin "airplay_emulation"...
1970-01-01T00:00:23.058Z - info: [23058] Starting Shairport Sync
1970-01-01T00:00:23.061Z - info: Loading plugin "mpd"...
1970-01-01T00:00:23.119Z - info: Loading plugin "networkfs"...
1970-01-01T00:00:23.166Z - info: Loading plugin "alarm-clock"...
1970-01-01T00:00:23.381Z - info: Loading plugin "webradio"...
1970-01-01T00:00:24.144Z - info: Loading plugin "albumart"...
1970-01-01T00:00:24.164Z - info: Plugin example_plugin is not enabled
1970-01-01T00:00:24.165Z - info: Loading plugin "updater_comm"...
1970-01-01T00:00:24.365Z - info: Plugin mpdemulation is not enabled
1970-01-01T00:00:24.366Z - info: Loading plugin "websocket"...
1970-01-01T00:00:24.398Z - info: Loading plugin "spop"...
1970-01-01T00:00:25.186Z - info: Applying required configuration parameters for plugin spop
1970-01-01T00:00:25.196Z - info: ___________ START PLUGINS ___________
1970-01-01T00:00:25.202Z - info: CoreCommandRouter::volumioAddToBrowseSources[object Object]
1970-01-01T00:00:25.204Z - info: [25203] CoreMusicLibrary::Adding element Webradio
1970-01-01T00:00:25.229Z - info: Loading i18n strings for locale en
1970-01-01T00:00:25.239Z - info: MPD I18N LOAD FOR LOCALE en
1970-01-01T00:00:25.292Z - info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
1970-01-01T00:00:25.293Z - info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
1970-01-01T00:00:25.294Z - info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
1970-01-01T00:00:25.295Z - info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
1970-01-01T00:00:25.295Z - info: CoreCommandRouter::executeOnPlugin: alsa_controller , getConfigParam
1970-01-01T00:00:25.309Z - info: BOOT COMPLETED
1970-01-01T00:00:25.351Z - info: [25350] CoreStateMachine::resetVolumioState
1970-01-01T00:00:25.352Z - info: [25352] CoreStateMachine::getcurrentVolume
1970-01-01T00:00:25.353Z - info: CoreCommandRouter::volumioRetrievevolume
1970-01-01T00:00:25.403Z - info: [25401] CoreStateMachine::updateTrackBlock
1970-01-01T00:00:25.406Z - info: [25404] CorePlayQueue::getTrackBlock
1970-01-01T00:00:25.504Z - info: SpopD Daemon Started
1970-01-01T00:00:25.522Z - info: MPD running with PID493 ,establishing connection
1970-01-01T00:00:25.554Z - info: Setting Device type: Raspberry PI 2/3
1970-01-01T00:00:25.579Z - info: [25577] VolumeController:: Volume=20 Mute =false
1970-01-01T00:00:25.582Z - info: [25581] CoreStateMachine::pushState
1970-01-01T00:00:25.583Z - info: [25582] CoreStateMachine::getState
1970-01-01T00:00:25.584Z - info: [25584] CorePlayQueue::getTrack 0
1970-01-01T00:00:25.586Z - info: CoreCommandRouter::volumioPushState
1970-01-01T00:00:25.586Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
1970-01-01T00:00:25.589Z - info: [25588] InterfaceWebUI::pushState
1970-01-01T00:00:25.690Z - info: Reloading queue from file
1970-01-01T00:00:25.736Z - info: Setting volume on startup at disabled
1970-01-01T00:00:25.750Z - info: 
1970-01-01T00:00:25.757Z - info: 
[25756] ---------------------------- Client requests Volume disabled
1970-01-01T00:00:25.761Z - info: [25760] VolumeController::SetAlsaVolumedisabled
1970-01-01T00:00:25.775Z - info: [25774] ------------------------------ 18ms
1970-01-01T00:00:25.778Z - info: Cannot call home: Error: Command failed: /usr/bin/curl -X POST --data-binary "device=pi&variante=volumio&version=0.928&uuid=b47a1f75e0bb3eeb149a03a2e8c78228" http://updates.volumio.org:7070/downloader-v1/track-device
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: updates.volumio.org

1970-01-01T00:00:25.807Z - info: [25807] VolumeController::Volume 100
1970-01-01T00:00:25.809Z - info: [25808] CoreStateMachine::pushState
1970-01-01T00:00:25.810Z - info: [25809] CoreStateMachine::getState
1970-01-01T00:00:25.811Z - info: [25810] CorePlayQueue::getTrack 0
1970-01-01T00:00:25.812Z - info: CoreCommandRouter::volumioPushState
1970-01-01T00:00:25.813Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
1970-01-01T00:00:25.816Z - info: [25814] InterfaceWebUI::pushState
1970-01-01T00:00:25.833Z - info: Pushing Favourites {"service":"mpd","uri":"","favourite":false}
1970-01-01T00:00:25.837Z - info: Pushing Favourites {"service":"mpd","uri":"","favourite":false}
1970-01-01T00:00:25.888Z - info: [25887] Shairport-Sync Started
1970-01-01T00:00:25.906Z - info: Upmpdcli Daemon Started
1970-01-01T00:00:30.512Z - info: Connecting to daemon
1970-01-01T00:00:30.583Z - info: SPOP command error:
1970-01-01T00:00:30.586Z - info:  Error: connect ECONNREFUSED 127.0.0.1:6602
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
1970-01-01T00:00:30.589Z - info: SPOP status error:
1970-01-01T00:00:30.590Z - info:  Error: connect ECONNREFUSED 127.0.0.1:6602
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
1970-01-01T00:00:39.700Z - info: mDNS: Found device Volumio2
1970-01-01T00:00:41.783Z - info: mDNS: A device disapperared from network
1970-01-01T00:00:49.463Z - info: mDNS: Found device Volumio2
1970-01-01T00:00:51.578Z - info: mDNS: A device disapperared from network
1970-01-01T00:01:17.094Z - info: mDNS: Found device Volumio2
1970-01-01T00:01:18.421Z - info: CoreCommandRouter::executeOnPlugin: appearance , getUiSettings
1970-01-01T00:01:18.478Z - info: CoreCommandRouter::volumioGetState
1970-01-01T00:01:18.479Z - info: [78478] CoreStateMachine::getState
1970-01-01T00:01:18.479Z - info: [78479] CorePlayQueue::getTrack 0
1970-01-01T00:01:18.481Z - info: 
[78480] ---------------------------- Client requests Volumio state
1970-01-01T00:01:18.483Z - info: [78483] InterfaceWebUI::pushState
1970-01-01T00:01:18.488Z - info: [78487] ------------------------------ 10ms
1970-01-01T00:01:18.497Z - info: [78496] Listing playlists
1970-01-01T00:01:18.512Z - info: CoreCommandRouter::executeOnPlugin: multiroom , getMultiroom
1970-01-01T00:01:18.514Z - info: 
[78514] ---------------------------- Client requests Menu Items
1970-01-01T00:01:18.551Z - info: [78550] ------------------------------ 36ms
1970-01-01T00:01:19.618Z - info: 
[79618] ---------------------------- Client requests Volume 100
1970-01-01T00:01:19.620Z - info: [79619] VolumeController::SetAlsaVolume100
1970-01-01T00:01:19.631Z - info: [79631] ------------------------------ 14ms
1970-01-01T00:01:19.639Z - info: [79638] VolumeController::Volume 100
1970-01-01T00:01:19.639Z - info: [79639] CoreStateMachine::pushState
1970-01-01T00:01:19.640Z - info: [79640] CoreStateMachine::getState
1970-01-01T00:01:19.641Z - info: [79640] CorePlayQueue::getTrack 0
1970-01-01T00:01:19.642Z - info: CoreCommandRouter::volumioPushState
1970-01-01T00:01:19.645Z - info: CoreCommandRouter::executeOnPlugin: volumiodiscovery , saveDeviceInfo
1970-01-01T00:01:19.646Z - info: [79646] InterfaceWebUI::pushState
1970-01-01T00:01:19.654Z - info: Pushing Favourites {"service":"mpd","uri":"","favourite":false}
2016-07-02T00:43:06.084Z - info: CoreCommandRouter::getUIConfigOnPlugin
2016-07-02T00:43:06.118Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:06.149Z - info: CoreCommandRouter::executeOnPlugin: networkfs , listShares
2016-07-02T00:43:10.128Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:10.915Z - info: mDNS: A device disapperared from network
2016-07-02T00:43:11.076Z - info: mDNS: Found device Volumio2
2016-07-02T00:43:14.127Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:18.134Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:22.143Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:26.137Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:30.139Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:34.142Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:38.143Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:42.148Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:46.148Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:50.475Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:43:55.477Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:44:10.474Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:44:23.474Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:44:28.032Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:44:36.076Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:44:40.077Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:44:44.077Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:44:48.080Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:44:52.090Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:44:56.085Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:45:00.091Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:45:04.096Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
2016-07-02T00:45:08.098Z - info: CoreCommandRouter::executeOnPlugin: mpd , getMyCollectionStats
volumio@volumio2:/var/log$

**Comment by skikirkwood** [comment]
Update, I've hit Rescan several times, and got up to a little over 19,000 tracks, so still missing 2000 or so.  Hitting Rescan now doesn't seem to initiate a rescan although I do see the command actions in the log file.

**Comment by apinner** [comment]
Do you know the file type that isn't scanning?

Is it mp4 or m4a with embedded artwork by any chance?

**Comment by skikirkwood** [comment]
I don't believe there is any embedded artwork from what I can see, however when I delete the shares and start over, the scan seems to stop reliably at a Clannad folder, which has track names with special characters in them (Irish/Celtic), so perhaps that is causing an issue.

I'm setting up a dev environment, so I'll try to add some additional logging into the scanning process and try to narrow down the problem further.

**Comment by apinner** [comment]
We had something similar here; https://github.com/volumio/Volumio2/issues/285

**Comment by skikirkwood** [comment]
To test I will delete the Clannad folder and start a rescan from scratch, along with putting some additional logging in my dev environment to see exactly what track is killing it.

**Comment by skikirkwood** [comment]
Here's an update.  I successfully got my entire music library scanned, but it took a total of 6 scans.  The last few times I just initiated the scan using "mpc update" in a terminal window.

After removing folders of music at and nearby where the first scan stopped I unmounted the network drive, remounted it and started a new scan from scratch.  The scan stopped at the same number of tracks as the previous time, although there was different music now where the scan stopped.  No embedded images, ordinary ALAC files.

After starting a new scan, it then stopped at the same number of tracks as the first round, but again, because I had moved out folders of music the stopping point of the last track scanned was different.

After 6 scans I got through all 21,011 tracks.

Another oddity is "mpc stats" shows a 21,011 tracks whereas Volumio's My Music shows 20,976.  Both show the same number artists and albums.

Volumio uses a custom build of MPD, right?  If so, adding a detailed logging function, if one isn't already there, would be very helpful.

**Comment by apinner** [comment]
mpd was actually updated today to the latest version https://github.com/volumio/Build/commit/6b9a38607bb615ac632b83b546b35aa7c9580878

**Comment by skikirkwood** [comment]
Thanks, grabbing it right now and will do a rescan from a new mount and see how it works.

**Comment by skikirkwood** [comment]
Just grabbed the newest mpd but it's not starting.  Is there an easy way to launch it, or would it be better for me to build an entirely new image for my RPi?

**Comment by volumio** [comment]
No it should start without any problem... Make sure you got the right version (arm or x86)

**Comment by skikirkwood** [comment]
Ok, got it going.  Will remove my mounted network drive, mount it back, rescan and let's see if we can get to 21,000 tracks the first time.

**Comment by volumio** [comment]
Fingersi crossed...

**Comment by skikirkwood** [comment]
Unfortunately the new MPD didn't solve the problem of the scanning stopping prematurely.  Is stopped at exactly the same place - 3313 tracks.  I just did a new rescan and let's see if it stops at 16,137 tracks like the last time.

I started up MPD with verbose logging to see what is going on.  It generates a huge number of errors about metadata for just about all of my tracks, which I assume is fine.  Here's the tail end of the log when it stopped - no errors - seemed to think it was done.  BTW, no problems with Volumio 1.55 scanning the same network drive, and if I recall correctly, Volumio 2 RC1 had a successful one pass scan.

update: added NAS/iTunes/Clarence Clemons/Hero/07 Cross the Line.m4a
update: reading NAS/iTunes/Clarence Clemons/Hero/08 Kissin' On U.m4a
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: ISO: File Type Major Brand: M4A
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unhandled or malformed custom metadata of size 95
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unhandled or malformed custom metadata of size 154
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unhandled or malformed custom metadata of size 112
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unhandled or malformed custom metadata of size 149
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: All info found
update: added NAS/iTunes/Clarence Clemons/Hero/08 Kissin' On U.m4a
update: reading NAS/iTunes/Clarence Clemons/Hero/09 Christina.m4a
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: ISO: File Type Major Brand: M4A
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unhandled or malformed custom metadata of size 95
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unhandled or malformed custom metadata of size 154
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unhandled or malformed custom metadata of size 112
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: Unhandled or malformed custom metadata of size 149
ffmpeg/mov,mp4,m4a,3gp,3g2,mj2: All info found
update: added NAS/iTunes/Clarence Clemons/Hero/09 Christina.m4a
simple_db: removing empty directories from DB
simple_db: sorting DB
simple_db: writing DB
client: [2] process command "status"
client: [2] command returned 0
update: finished

**Comment by apinner** [comment]
Bugger!

**Comment by skikirkwood** [comment]
Good news, I found that when I removed the track alphabetically ahead of where the scan stopped the first time I got all the way to 16,737 tracks on the first scan.  It's an ALAC Tiesto track, not sure why it caused problems.

Having unmounted my network share and remounting it several times now to debug this, I now have a problem where after removing the network share and checking /mnt/NAS is empty, the iTunes folder mysteriously shows up and stops me from remounting the drive.  I think this was reported earlier.  A few reboots are in order, but it looks like the problem was due to issues with a few tracks, although MPD in Volumio 1.55 didn't have any issues with them.

**Comment by apinner** [comment]
Could it be the ë in Tiësto thats causing the issue? Which would actually point towards the issue that i mentioned before.

**Comment by skikirkwood** [comment]
That was my guess. After I figure out how to get not network drive mounted again I'll try some more scans. Didn't see any special characters around the tracks where it stopped at 16000 though.   
  

  
I could also create a new network library with these problematic tracks in it and use it as a test case.   
  
  
  

  
  
>

**Comment by skikirkwood** [comment]
Latest version works perfectly. Closing this.
