### ISSUE TITLE
[RC2 hotfix] Volumio2 stops working after installing spotify plugin

### ISSUE THREAD

**Issue by silliboy** [volumio/Volumio2#515]
Volumio stops working after installing spotify plugin.
Reason: Selected sytem language is german and no "strings_de.json" file is present at /data/plugins/music_service/spop/i18n.
Possible solution: Make a fallback routine to the english language if no translation for the plugin has been found.
log is here:
`2016-07-02T21:14:20.041Z - info: Enabling plugin spop
2016-07-02T21:14:20.046Z - info: Loading plugin "spop"...
2016-07-02T21:14:21.011Z - info: SpopD Daemon Started
2016-07-02T21:14:24.348Z - info: CoreCommandRouter::getUIConfigOnPlugin
2016-07-02T21:14:24.357Z - info: ERROR LOADING JSON Error: ENOENT: no such file or directory, open '/data/plugins/music_service/spop/i18n/strings_de.json'
2016-07-02T21:14:26.015Z - info: Connecting to daemon
2016-07-02T21:14:26.036Z - info: SPOP command error:
2016-07-02T21:14:26.039Z - info:  Error: connect ECONNREFUSED 127.0.0.1:6602
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
2016-07-02T21:14:26.041Z - info: SPOP status error:
2016-07-02T21:14:26.042Z - info:  Error: connect ECONNREFUSED 127.0.0.1:6602
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)
2016-07-02T21:14:27.352Z - info: [{"prettyName":"Spotify","name":"spop","cat`

**Comment by silliboy** [comment]
seems to work now.
