### ISSUE TITLE
removal of standaard available background images fails

### ISSUE THREAD

**Issue by WalterBorgstein** [volumio/Volumio2#662]
On RPI3
Volumio version : 0.978

- Own backgrounds can be removed after adding them.

```
Aug 20 16:18:19 volumio volumio[3235]: info: CoreCommandRouter::getUIConfigOnPlugin
Aug 20 16:18:19 volumio volumio[3235]: info: CoreCommandRouter::executeOnPlugin: appearance , getBackgrounds
Aug 20 16:18:23 volumio volumio[3235]: info: CoreCommandRouter::executeOnPlugin: appearance , deleteBackgrounds
Aug 20 16:18:23 volumio volumio[3235]: /volumio/app/plugins/miscellanea/appearance/index.js:359
Aug 20 16:18:23 volumio volumio[3235]: self.commandRouter.pushToastMessage('success', self.getI18NString('appearance_title'),
Aug 20 16:18:23 volumio volumio[3235]: ^
Aug 20 16:18:23 volumio volumio[3235]: TypeError: self.getI18NString is not a function
Aug 20 16:18:23 volumio volumio[3235]: at /volumio/app/plugins/miscellanea/appearance/index.js:359:77
Aug 20 16:18:23 volumio volumio[3235]: at FSReqWrap.oncomplete (fs.js:123:15)
Aug 20 16:18:23 volumio mpd[621]: client: [6] closed

```

**Comment by volumio** [comment]
fixed https://github.com/volumio/Volumio2/commit/913bfc0d191a11b9aef76c6ae8138df3bf6c4a87
