### ISSUE TITLE
Regression on RpiB+ with update from 2.001 to 2.002

### ISSUE THREAD

**Issue by heis2201** [volumio/Volumio2#787]
Just updated from 2.001 (which was working OK) to 2.002 and as a result I can't reach the WebUI anymore.

ssh to volumio works,

`journalctl -f` says:

```
Oct 20 16:38:18 volumio volumio[1465]: info: -------------------------------------------
Oct 20 16:38:18 volumio volumio[1465]: info: -----            Volumio2              ----
Oct 20 16:38:18 volumio volumio[1465]: info: -------------------------------------------
Oct 20 16:38:18 volumio volumio[1465]: info: -----          System startup          ----
Oct 20 16:38:18 volumio volumio[1465]: info: -------------------------------------------
Oct 20 16:38:18 volumio volumio[1465]: fs.js:951
Oct 20 16:38:18 volumio volumio[1465]: return binding.readdir(pathModule._makeLong(path), options.encoding);
Oct 20 16:38:18 volumio volumio[1465]: ^
Oct 20 16:38:18 volumio volumio[1465]: Error: ENOENT: no such file or directory, scandir '/volumio/update'
Oct 20 16:38:18 volumio volumio[1465]: at Error (native)
Oct 20 16:38:18 volumio volumio[1465]: at Object.fs.readdirSync (fs.js:951:18)
Oct 20 16:38:18 volumio volumio[1465]: at CoreCommandRouter.checkAndPerformSystemUpdates (/volumio/app/index.js:899:18)
Oct 20 16:38:18 volumio volumio[1465]: at new CoreCommandRouter (/volumio/app/index.js:37:10)
Oct 20 16:38:18 volumio volumio[1465]: at Object.<anonymous> (/volumio/index.js:34:21)
Oct 20 16:38:18 volumio volumio[1465]: at Module._compile (module.js:541:32)
Oct 20 16:38:18 volumio volumio[1465]: at Object.Module._extensions..js (module.js:550:10)
Oct 20 16:38:18 volumio volumio[1465]: at Module.load (module.js:458:32)
Oct 20 16:38:18 volumio volumio[1465]: at tryModuleLoad (module.js:417:12)
Oct 20 16:38:18 volumio volumio[1465]: at Function.Module._load (module.js:409:3)
Oct 20 16:38:18 volumio systemd[1]: volumio.service: main process exited, code=exited, status=1/FAILURE
Oct 20 16:38:18 volumio systemd[1]: Unit volumio.service entered failed state.
Oct 20 16:38:18 volumio systemd[1]: Starting dynamicswap.service...
Oct 20 16:38:18 volumio systemd[1]: Started dynamicswap.service.
Oct 20 16:38:18 volumio systemd[1]: volumio.service holdoff time over, scheduling restart.
Oct 20 16:38:18 volumio systemd[1]: Stopping Volumio Backend Module...
Oct 20 16:38:18 volumio systemd[1]: Starting Volumio Backend Module...
Oct 20 16:38:18 volumio systemd[1]: Started Volumio Backend Module.
Oct 20 16:38:18 volumio volumio[1480]: 512 MB or less RAM Detected, need to enable swap
Oct 20 16:38:18 volumio volumio[1480]: Enabling Swap
Oct 20 16:38:19 volumio volumio[1480]: swapon: /data/swapfile: swapon failed: Device or resource busy
Oct 20 16:38:19 volumio systemd[1]: dynamicswap.service: main process exited, code=exited, status=255/n/a
Oct 20 16:38:19 volumio systemd[1]: Unit dynamicswap.service entered failed state.
```

Is there a way to fix this?

**Comment by volumio** [comment]
2.0002 is a dev release, only way to fix it: reflash 2.001
